### ISSUE TITLE
How to download recorded sound as .wav file?

### ISSUE THREAD

**Issue by OneCodePeasant** [michalstocki/FlashWavRecorder#43]
Hi, i have come across with a problem by the fllow case:
i want to user the interface named 'getBase64' and 'getBlob',
but when i use the return result,it can not be played;
fllowing is my main code
part of recorder.js:
```javascript
var getWav = function(){
    var blobtemp = base64toBlob(base64Data, RECORDED_AUDIO_TYPE);
    $("#audioa").attr("src",window.URL.createObjectURL(blobtemp)); 
};
```
part of html:
getWav

after i click the button 'getWav' i cannot get my voice...
(i want to get the wav and deal with it to let it be smaller)
can you help me?
thank you!

**Comment by michalstocki** [comment]
Hi,
I assume that `$("#audioa")` selects `<a id="audioa">getWav</a>`. I this case you should use attr `href` instead of `src`:

```javascript
  $("#audioa").attr("href", window.URL.createObjectURL(blobtemp)); 
```

**Comment by michalstocki** [comment]
Here is complete working code for downloading recorded sound as .wav file:
```javascript
var saveRecording = function (recordingName) {
    var a = document.createElement("a");
    document.body.appendChild(a);
    a.style = "display: none";
    var blob = FWRecorder.getBlob(recordingName),
        url = window.URL.createObjectURL(blob);
    a.href = url;
    a.download = recordingName + '-fwr-recording.wav';
    a.click();
    window.URL.revokeObjectURL(url);
    document.body.removeChild(a);
};

saveRecording('audio');
```

**Comment by OneCodePeasant** [comment]
Yeah,i also find the problem ,thanks! By the way ,can you help me reduce the size of the wav file?-.-

**Comment by michalstocki** [comment]
We can reduce the size of the .wav file by converting it to mp3. There is issue #6 on this topic
