### ISSUE TITLE
How to upload with JavaScript code?

### ISSUE THREAD

**Issue by yolo2013** [michalstocki/FlashWavRecorder#45]
How can I upload the wav audio with JS code. For jQuery, something like $('#upload_form').upload()

**Comment by robinsmidsrod** [comment]
You need to use either the getBlob() or getBase64() methods, depending on how compatible you want to be. If you use getBlob(), then the FormData API in your browser might be of use.

**Comment by michalstocki** [comment]
Here are all the details: https://github.com/michalstocki/FlashWavRecorder/wiki
