### ISSUE TITLE
Make the recorder to auto stop at any given time. e.g 30secs, or 1 minute time limit

### ISSUE THREAD

**Issue by sancel22** [michalstocki/FlashWavRecorder#48]

**Comment by robinsmidsrod** [comment]
I don't quite understand why you need this. It should be trivial to use the existing API and a setTimeout() JS call to trigger a stop or pause after whatever time you want. What is your reasoning for having this as an API feature?

**Comment by sancel22** [comment]
@robinsmidsrod yeah! Maybe I can do as what you had suggested. Thank you very much :smile:
