### ISSUE TITLE
Need help setting this up.

### ISSUE THREAD

**Issue by sancel22** [michalstocki/FlashWavRecorder#49]
Hi I set this up on my cakePHP project. I had loaded the files, ` swfobject.js ` ` recorder.js ` and basically just using the ` basic.js `. But when I clicked my record button it gives me this error. 
``` 
TypeError: Recorder.recorder is null
Recorder.recorder.record(name, filename);
```
Is there something that I missed?

**Comment by michalstocki** [comment]
You need also to put `recorder.swf` file on your server. Additionally it's needed to embed swf file:

    swfobject.embedSWF("../recorder.swf", "flashcontent", appWidth, appHeight, "11.0.0", "", flashvars, params, attributes);

Example embedding here: https://github.com/michalstocki/FlashWavRecorder/blob/master/html/basic/basic.js It assumes that you have some html element on your page with `id="flashcontent"`

**Comment by sancel22** [comment]
Thank you for your reply @michalstocki but I also make sure ` recorder.swf ` was loaded and have a ` div ` with ` id=flashcontent ` in it. 

Regards,

**Comment by sancel22** [comment]
Found the problem already,, Somehow on my cakePHP it's doesn't work given a relative path for ` recorder.swf ` so instead I provided the absolute path. Thanks
