### ISSUE TITLE
Safari issue with Blob

### ISSUE THREAD

**Issue by tehmaestro** [michalstocki/FlashWavRecorder#52]
Hi, I get this error in Safari 5, Windows 7:
`'[object BlobConstructor]' is not a constructor (evaluating 'new Blob(byteArrays, {type: contentType})')`

Any idea how I can fix this? I tried importing this https://github.com/eligrey/Blob.js/ 

Also looked into this: http://stackoverflow.com/questions/14347534/blob-constructor-not-working-in-safari-opera . But It doesn't work.

**Comment by michalstocki** [comment]
It seems that safari 5 does not support `BlobBuilder` (deprecated API) nor Blob constructor (syntax with `new Blob`. That's why Blob.js is useless.
http://caniuse.com/#search=blob

**Comment by tehmaestro** [comment]
Ok, thank you. Also, there seems to be a problem with browsers that have getUserMedia. (native support for microphone). I tried your example in Chrome latest version, and I could not playback nor record.

**Comment by michalstocki** [comment]
Oups. That's a serious problem. I investigated this problem and created the new issue #53.
