### ISSUE TITLE
Can't find microphone on IE8 Windows XP

### ISSUE THREAD

**Issue by stalwartwill** [michalstocki/FlashWavRecorder#55]
Hi there Michal,

First of all, thank you very much for this great tool.

I'm using it to capture audio on our web project:

However, for some reason the recorder is failing to record and the "fwr_event_handler" handler always  give "microphone_not_connected"  in IE 8. It's working fine chrome.
I've tested my micriphone by system audio manager and it work fine.

Any help or advice you could give would be very much appreciated.

Many thanks in advance,

**Comment by stalwartwill** [comment]
I've find the reason that FlashVavRecorder cannot find microphone and the fwr_event_handler receive "microphone_not_connected", the reason is the configuration of flash in mms.cfg（the file path under xp is C:\WINDOWS\system32\Macromed\Flash\mms.cfg)，and you can open flash configuration dialog on system control panel, and you'll find that the microphone and camera is disabled. set AVHardwareDisable=1 in mms.cfg and the problem will be solved.

**Comment by michalstocki** [comment]
Wow! The solution is quite advanced. Thank you for contribution.
