### ISSUE TITLE
MediaStreamRecorder landing in Chromium

### ISSUE THREAD

**Issue by jsalsman** [michalstocki/FlashWavRecorder#58]
https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/2l_G_apqk30

https://code.google.com/p/chromium/issues/detail?id=262211

**Comment by michalstocki** [comment]
Yep, I know that we could implement audio recording using HTML5. Almost all modern browsers support it currently. More on this topic, I posted in issue #54
