### ISSUE TITLE
Slow blob creation

### ISSUE THREAD

**Issue by michaelwoods** [michalstocki/FlashWavRecorder#72]
I am testing this library on a VM (4GB ram, Win 7, IE 11, i7 CPU) and found that the getBlob() function is very slow to generate a Blob. The recording being exported is approximately 8 minutes and the export required 7 minutes to complete at the higher end of the measurements.

```
Recording export started Mon Oct 24 2016 09:45:02 GMT-0700 (Pacific Daylight Time)
Recording export complete Mon Oct 24 2016 09:52:09 GMT-0700 (Pacific Daylight Time)
```

On actual Windows machines the export is faster but remains on the order of several minutes. Is this inline with what you would expect for a longer recording?

**Comment by michaelwoods** [comment]
I've added a PR to handle this situation: #73

**Comment by michalstocki** [comment]
@michaelwoods great thanks for your contribution! That's really nice that you've investigated this problem. I've never recorded as long files. That were usually 10 second samples.

**Comment by michalstocki** [comment]
@michaelwoods as we know, the solution proposed in #73 will not work – we are not able to send binary data (encoded wav) through the Flash ExternalInterface.
I was thinking a bit, searching a possible solution for the "slow blob creation". I agree, that the blob export for long recording is horribly slow. As you've mentioned, a time needed to export the `Blob` object is _almost_ as long as a time of the recording. This suggests that we could try to send a sound data from Flash to a JavaScript concurrently while the recording is in progress. We could also try to incrementally encode the WAV object on the JavaScript side while the recording is in progress.
What's more important, all we need from the Flash to achieve the ideas described above, is already available. We just need to listen for the `microphone_samples` event:

``` javascript
window.fwr_event_handler = function fwr_event_handler() {
    switch (arguments[0]) {
      case "ready":
        // ...
        FWR.observeSamples();    // enable emitting the "microphone_samples" event

      case "microphone_samples":
        var samples = arguments[1];
        // collect samples or encode into a WAV
        break;
};
```

[Encoding sound into a WAV](https://github.com/daaain/JSSoundRecorder/tree/gh-pages/js/lib) file in a JavaScript is a part of a [JSSoundRecorder](https://github.com/daaain/JSSoundRecorder). Of course, you can use this library also for recording the sound.
I hope this helps.

**Comment by michaelwoods** [comment]
@michalstocki that worked as you expected, managing the audio samples within JS resulted in the WAV export process being similar to using the Web Audio APIs. Thanks for the suggestion, this issue can be closed.
